language: c
language: cpp

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get -q install protobuf-compiler libprotobuf-dev libprotoc-dev
      valgrind

script:
    - ./autogen.sh
    - ./configure && make distcheck VERBOSE=1 && make clean
    - ./configure --enable-valgrind-tests && make distcheck
      DISTCHECK_CONFIGURE_FLAGS="--enable-valgrind-tests" VERBOSE=1
